mail:
  from: nguyenvantrungnct@gmail.com
gravatar:
  size: 30
name_user:
  maximum: 50
tel:
  maximum: 30
  minimum: 9
email:
  maximum: 255
password:
  minimum: 6
home:
  url: http://localhost:3000/
booking:
  url: https://www.booking.com/
sessions:
  default_check: 1
picture:
  type: "image/jpeg,image/gif,image/png"
  size: 30
tours:
  per_page: 5
